stages:
  download_data:
    cmd: py ./refactoring/descargarDatadeZipACSV.py
    deps:
      - refactoring/descargarDatadeZipACSV.py
      - refactoring/loadParams.py
    outs:
      - ${data.downloadPath}/${data.cirrhosisNombreArchivo}.csv
  load_Data:
    cmd: py ./refactoring/cargarData.py
    deps:
      - ./refactoring/cargarData.py
      - ./refactoring/EDA.py
      - ${data.downloadPath}/${data.cirrhosisNombreArchivo}.csv
      - ./refactoring/loadParams.py
    outs:
      - ${data.basePath}/${data.cirrhosisNombreArchivo}.csv
  split_Data:
    cmd: py ./refactoring/splitData.py
    deps: 
      - ./refactoring/splitData.py
      -  ${data.basePath}/${data.cirrhosisNombreArchivo}.csv
      - ./refactoring/EDA.py
      - refactoring/loadParams.py
    outs:
      - ${data.basePath}/X_test.csv
      - ${data.basePath}/y_test.csv
      - ${data.basePath}/X_val.csv
      - ${data.basePath}/y_val.csv
      - ${data.basePath}/X_train.csv
      - ${data.basePath}/y_train.csv
  pre_process:
    cmd: py ./refactoring/preprocess.py ${data.basePath}/ ${data.preprocesdePath}/
    deps: 
      - ./refactoring/preprocess.py
      - ${data.basePath}/X_test.csv
      - ${data.basePath}/y_test.csv
      - ${data.basePath}/X_val.csv
      - ${data.basePath}/y_val.csv
      - ${data.basePath}/X_train.csv
      - ${data.basePath}/y_train.csv
    outs:
      - ${data.preprocesdePath}/X_test.csv
      - ${data.preprocesdePath}/y_test.csv
      - ${data.preprocesdePath}/X_val.csv
      - ${data.preprocesdePath}/y_val.csv
      - ${data.preprocesdePath}/X_train.csv
      - ${data.preprocesdePath}/y_train.csv
  entrenar-modelos:
    cmd: py ./refactoring/entrenarModelos.py ${data.preprocesdePath}/ ${modelos.path}/
    deps: 
      - ./refactoring/entrenarModelos.py
      - ${data.preprocesdePath}/X_test.csv
      - ${data.preprocesdePath}/y_test.csv
    outs:
      - ${modelos.path}/modeloRegLog.sav
      - ${modelos.path}/modeloXGBoost.sav
  evaluar-modelos:
    cmd: py ./refactoring/evaluarModelos.py ${data.preprocesdePath}/ ${modelos.path}/
    deps: 
      - ${data.preprocesdePath}/X_test.csv
      - ${data.preprocesdePath}/y_test.csv
      - ${data.preprocesdePath}/X_val.csv
      - ${data.preprocesdePath}/y_val.csv
      - ${data.preprocesdePath}/X_train.csv
      - ${data.preprocesdePath}/y_train.csv
      - ${modelos.path}/modeloRegLog.sav
      - ${modelos.path}/modeloXGBoost.sav
      - ${modelos.path}/modeloXGBoost.sav

 
