stages:
  download_data:
    cmd: py ./refactoring/descargarDatadeZipACSV.py ${data.url} ${data.downloadPath} ${data.cirrhosisZipFileName}
    deps:
      - refactoring/descargarDatadeZipACSV.py
    outs:
      - ${data.downloadPath}/${data.cirrhosisCsvFileName}
  load_Data:
    cmd: py ./refactoring/cargarData.py ${data.downloadPath}/${data.cirrhosisCsvFileName} ${data.basePath}/${data.cirrhosisCsvFileName}
    deps:
      - ./refactoring/cargarData.py
      - ./refactoring/EDA.py
      - ${data.downloadPath}/${data.cirrhosisCsvFileName}
    outs:
      - ${data.basePath}/${data.cirrhosisCsvFileName}
  split_Data:
    cmd: py ./refactoring/splitData.py ${data.basePath}/${data.cirrhosisCsvFileName} ${data.basePath}/
    deps: 
      - ./refactoring/splitData.py
      -  ${data.basePath}/${data.cirrhosisCsvFileName}
      - ./refactoring/EDA.py
    outs:
      - ${data.basePath}/X_test.csv
      - ${data.basePath}/y_test.csv
      - ${data.basePath}/X_val.csv
      - ${data.basePath}/y_val.csv
      - ${data.basePath}/X_train.csv
      - ${data.basePath}/y_train.csv
  pre_process:
    cmd: py ./refactoring/preprocess.py ${data.basePath}/ ${data.preprocesdePath}/
    deps: 
      - ./refactoring/preprocess.py
      - ${data.basePath}/X_test.csv
      - ${data.basePath}/y_test.csv
      - ${data.basePath}/X_val.csv
      - ${data.basePath}/y_val.csv
      - ${data.basePath}/X_train.csv
      - ${data.basePath}/y_train.csv
    outs:
      - ${data.preprocesdePath}/X_test.csv
      - ${data.preprocesdePath}/y_test.csv
      - ${data.preprocesdePath}/X_val.csv
      - ${data.preprocesdePath}/y_val.csv
      - ${data.preprocesdePath}/X_train.csv
      - ${data.preprocesdePath}/y_train.csv
  entrenar-modelos:
    cmd: py ./refactoring/entrenarModelos.py ${data.preprocesdePath}/ ${modelos.path}/
    deps: 
      - ${data.preprocesdePath}/X_test.csv
      - ${data.preprocesdePath}/y_test.csv
    outs:
      - ${modelos.path}/modeloRegLog.sav
      - ${modelos.path}/modeloXGBoost.sav

 
