data:
  url: "https://archive.ics.uci.edu/static/public/878/cirrhosis+patient+survival+prediction+dataset-1.zip"
  downloadPath: "data/download/"
  basePath: "data/base/"
  preprocesdePath: "data/preprocesed/"
  cirrhosisNombreArchivo: "cirrhosis"

modelos:
  path: "modelos"


mlflow:
  version: "v1"
  experiment_name: "Cirrhosis V1"
  tracking_uri: "http://127.0.0.1:5000"
