data:
  url: "https://archive.ics.uci.edu/static/public/878/cirrhosis+patient+survival+prediction+dataset-1.zip"
  downloadPath: "data/download/"
  basePath: "data/base/"
  preprocesdePath: "data/preprocesed/"
  cirrhosisNombreArchivo: "cirrhosis"

modelos:
  path: "modelos/"
  grid_logistico: [{
                        'penalty': ['l1', 'l2', 'elasticnet'],
                        'C': [0.01, 0.2, 3],
                        'solver': ['saga', 'lbfgs'],
                        'max_iter': [200, 250],
                        'tol': [1e-4, 1e-3],
                        'multi_class': ['ovr', 'multinomial']
                },
                {
                        'penalty': ['elasticnet'],
                        'C': [1, 6.001],
                        'solver': ['saga'],
                        'l1_ratio': [0, 1.6],
                        'class_weight': ['balanced']
                }]
  grid_xgboost: {
        'n_estimators': [100, 300],
        'learning_rate': [0.01, 0.05, 1],
        'max_depth': [2, 6],
        'subsample': [0.6, 1],
        'colsample_bytree': [0.6, 1],
        'min_child_weight': [1, 10],
        'lambda': [1, 10],
        'alpha': [0, 10],
        'use_label_encoder':["False"]
    }

pipelines:
  path: "pipelines/"


mlflow:
  experiment_name: "Cirrhosis V1"
  tracking_uri: "http://127.0.0.1:5000"
  run_name: "Run 1 fase 3"
