data:
  url: "https://archive.ics.uci.edu/static/public/878/cirrhosis+patient+survival+prediction+dataset-1.zip"
  downloadPath: "data/download/"
  basePath: "data/base/"
  preprocesdePath: "data/preprocesed/"
  cirrhosisNombreArchivo: "cirrhosis"

modelos:
  path: "modelos/"
  grid_logistico: [{
                        'penalty': ['l1', 'l2'],
                        'C': [0.001,0.002,0.003,0.004,0.005],
                        'solver': ['saga'],
                },
                {
                       'penalty': ['elasticnet'],
                        'C': [0.001,0.002,0.003,0.004,0.005],
                        'solver': ['saga'],
                        'l1_ratio': [0, 0.5, 1]  # Sólo para elasticnet 
                }]
  grid_xgboost: {
        'n_estimators': [50, 100, 200, 300 , 400, 500,350,400],
        'learning_rate': [0.001,0.002,0.003],
        'max_depth': [2,1,3,4],
        'subsample': [0.8,1,1.5,2],
        'use_label_encoder':["False"]
    }


mlflow:
  experiment_name: "Cirrhosis V1"
  tracking_uri: "http://127.0.0.1:5000"
