data:
  url: "https://archive.ics.uci.edu/static/public/878/cirrhosis+patient+survival+prediction+dataset-1.zip"
  downloadPath: "data/download/"
  basePath: "data/base/"
  preprocesdePath: "data/preprocesed/"
  cirrhosisNombreArchivo: "cirrhosis"

modelos:
  path: "modelos/"
  grid_logistico: [{
                        'penalty': ['l1', 'l2'],
                        'C': [2,2,2,2,2],
                        'solver': ['saga'],
                        'random_state': [45]
                },
                {
                       'penalty': ['elasticnet'],
                        'C': [2,2,2,2,2],
                        'solver': ['saga'],
                        'l1_ratio': [0.2, 0.4, 0.6, 0.8 ]  # Sólo para elasticnet 
                }]
  grid_xgboost: {
        'n_estimators': [100, 150, 200],
        'learning_rate': [0.003,0.5,0.5],
        'max_depth': [1,2,3,4,5],
        'subsample': [0.6,0.7,0.8],
        'use_label_encoder':["False"]
    }


mlflow:
  experiment_name: "Cirrhosis V1"
  tracking_uri: "http://127.0.0.1:5000"
