FROM python:3.9-slim

# Set the working directory
WORKDIR /app
COPY ./ /app/

# Install dependencies
RUN pip install fastapi numpy uvicorn pydantic python-dotenv pandas mlflow

# Expose port 8000
EXPOSE 8000

# Run the application
CMD ["uvicorn", "server:app", "--host", "0.0.0.0", "--port", "8000"]